### ISSUE TITLE
MetadataGraber error

### ISSUE THREAD

**Issue by Al-Ouest** [Ganapati/DjangoZik#3]
When running reset.sh, got this error :
```python
...
Superuser created successfully.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/alouest/Documents/DjangoZik/djangozik/management/commands/importmusic.py", line 7, in <module>
    from libs.metadataGrabber import MetadataGrabber
  File "/home/alouest/Documents/DjangoZik/libs/metadataGrabber.py", line 44
    print "test function"
                        ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by Al-Ouest** [comment]
After adding missing parentheses in metadataGrabber.py, got this one : 
```pyhton
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/alouest/Documents/DjangoZik/venv_django_zik/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/alouest/Documents/DjangoZik/djangozik/management/commands/importmusic.py", line 7, in <module>
    from libs.metadataGrabber import MetadataGrabber
  File "/home/alouest/Documents/DjangoZik/libs/metadataGrabber.py", line 3, in <module>
    from coverGrabber import CoverGrabber
ImportError: No module named 'coverGrabber'
```

**Comment by Ganapati** [comment]
First error : djangozik was written in python 2.7, parenthesis missing with print is for python 3.x
Second : No idea, need to check !

TODO : python 3.x support & fix metadata grabber
